### ISSUE TITLE
Contracts in npm module

### ISSUE THREAD

**Issue by j0x0j** [etherisc/GIF#2]
First of all, great job on the project. I was able to implement a product in a few hours. [GIF-Windstorm](https://github.com/teamraincoat/gif-windstorm), feel free to use the boilerplate and/or modify it.

I want to suggest that you publish and npm module with the source contracts so that it can be imported like `import "@etherisc/gif/contracts/InsuranceProduct.sol";` and so that it can be managed as a dev dependency.

Right now I just copied the gif-contracts directory over to my project's node_modules.

**Comment by kandrianov** [comment]
That’s great!) Thank you! Wrap the code into the npm module is definitely good idea. It will be soon.
