### ISSUE TITLE
First claim returns an id of zero

### ISSUE THREAD

**Issue by j0x0j** [etherisc/GIF#3]
I noticed that the first claim in https://github.com/teamraincoat/gif-windstorm/blob/master/contracts/Windstorm.sol#L149 always returns an id of `0`, is that the expected behavior? Should it return `1` for the first claim?

**Comment by kandrianov** [comment]
Indeed, interesting question.
The actual reason is because internally we use array to store claims. That’s why the key for the first element is expected to be 0. But what do you think, such objects like claims, policies etc should have indexes started from 1?

**Comment by j0x0j** [comment]
Understood, yes I would expect any auto-incrementing id to start from 1 for the first item. I'm not sure what side-effects it would create in the contracts though. My concern is in the client as 0 is a falsy value and could potentially cause unexpected behavior.

**Comment by christoph2806** [comment]
Closing this for now, due to overall rework.
